version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # - apt-get install python3-pip -y
      - apt-get install python3 -y
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python3 get-pip.py
      - pip3 install sphinx sphinx_rtd_theme sphinx-sitemap
      # - pip3 install guzzle_sphinx_theme
  build:
    commands:
      - cd docs/
      - make clean html

artifacts:
  files:
    - docs/build/html/**/*
    - appspec.yml
    - scripts/01-create-folder.sh
    - scripts/02-clean-build.sh
    - scripts/03-set-permissions.sh
  discard-paths: no